### ISSUE TITLE
Deploy to 599CD.com

### ISSUE THREAD

**Issue by AlexHedley** [599CD/glossary#17]
Use [FTP Deploy](https://github.com/marketplace/actions/ftp-deploy) to push to server

```yml
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ftp.samkirkland.com
        username: myFtpUserName
        password: ${{ secrets.ftp_password }}
        local-dir:./_site/
```
